# Generated by Django 3.1.1 on 2022-03-15 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True, unique=True)),
                ('nationality', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('United kingdom', 'United kingdom'), ('USA', 'USA')], max_length=20, null=True)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Osun', 'Osun'), ('Lagos', 'Lagos'), ('Kano', 'Kano'), ('Abuja', 'Abuja')], max_length=20, null=True)),
                ('means_of_identity', models.ImageField(null=True, upload_to='identityImage/')),
                ('particulars', models.FileField(null=True, upload_to='particularImage/')),
                ('profile_passport', models.ImageField(null=True, upload_to='staffImage/')),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('GMD', 'GMD'), ('CTO', 'CTO'), ('Supervisor', 'Supervisor'), ('Accountant', 'Accountant'), ('Marketer', 'Marketer'), ('Staff', 'Staff'), ('HR', 'HR')], max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('Divorced', 'Divorced'), ('complicated', 'complicated')], max_length=12, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
