# Generated by Django 3.1.1 on 2022-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('Divorced', 'Divorced'), ('complicated', 'complicated'), ('On God', 'On God')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('GMD', 'GMD'), ('CTO', 'CTO'), ('Supervisor', 'Supervisor'), ('Accountant', 'Accountant'), ('Receptionist', 'Receptionist'), ('Staff', 'Staff'), ('HR', 'HR'), ('Gateman', 'Gateman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Oyo', 'Oyo'), ('Osun', 'Osun'), ('Lagos', 'Lagos'), ('Kano', 'Kano'), ('Abuja', 'Abuja'), ('Ondo', 'Ondo')], max_length=20, null=True),
        ),
    ]
